version: '3.1'
services:
  client:
    image: nginx
    ports:
        - 80:80
    volumes:
        - ./src:/usr/share/nginx/html
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100